### PR TITLE
Converted all device and random device logs to the ocp diag format

### PR DESCRIPTION
**Pull request by dhawkes**
Internal reference: 274523023

### CODE REVIEW

**Comment by dhawkes** [comment]
Current dependencies on/for this PR:
* main
  * **PR #10** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/10" target="_blank">Graphite</a> 
    * **PR #12** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/12" target="_blank">Graphite</a> 
      * **PR #11** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/11" target="_blank">Graphite</a> 
        * **PR #13** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/13" target="_blank">Graphite</a> 
          * **PR #14** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/14" target="_blank">Graphite</a> 
            * **PR #15** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/15" target="_blank">Graphite</a> 
              * **PR #16** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/16" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/16?utm_source=stack-comment).

**Review by jcgao1 — APPROVED** [review]

**Comment by dhawkes** [comment]
@dhawkes started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/16).

**Comment by dhawkes** [comment]
@dhawkes started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/16).

**Comment by dhawkes** [comment]
@dhawkes merged this pull request with [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/16).

**Pull request merged**
