### PR TITLE
Removed error callback code which doesn't do anything in open source and only has meaning internally.

### PR DESCRIPTION
**Pull request by dhawkes**

### CODE REVIEW

**Comment by dhawkes** [comment]
Current dependencies on/for this PR:
* main
  * **PR #10** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/10" target="_blank">Graphite</a> 
    * **PR #12** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/12" target="_blank">Graphite</a>  👈
      * **PR #11** <a href="https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/11" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/12?utm_source=stack-comment).

**Comment by dhawkes** [comment]
@kimmidi cc

**Review by jcgao1 — APPROVED** [review]

**Comment by dhawkes** [comment]
@dhawkes queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/12).

**Comment by dhawkes** [comment]
@dhawkes queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/opencomputeproject/ocp-diag-sat/12).

**Pull request merged**
